import type { EditorThemeClasses } from "lexical";

const editorTheme: EditorThemeClasses = {
  heading: {
    h1: "blog-editor-h1",
    h2: "blog-editor-h2",
    h3: "blog-editor-h3",
    h4: "blog-editor-h4",
    h5: "blog-editor-h5",
  },
  list: {
    nested: {
      listitem: "blog-editor-nested-listitem",
    },
    ol: "blog-editor-list-ol",
    ul: "blog-editor-list-ul",
    listitem: "blog-editor-listitem",
    listitemChecked: "blog-editor-listitem-checked",
    listitemUnchecked: "blog-editor-listitem-unchecked",
  },
  // image: "blog-editor-image",
  link: "blog-editor-link",
  text: {
    bold: "blog-editor-text-bold",
    italic: "blog-editor-text-italic",
    underline: "blog-editor-text-underline",
    strikethrough: "blog-editor-text-strikethrough",
    underlineStrikethrough: "blog-editor-text-underline-strikethrough",
    code: "blog-editor-text-code",
    subscript: "blog-editor-text-subscript",
    superscript: "blog-editor-text-superscript",
  },
  code: "blog-editor-code",
  codeHighlight: {
    atrule: "blog-editor-tokenAttr",
    attr: "blog-editor-tokenAttr",
    boolean: "blog-editor-tokenProperty",
    builtin: "blog-editor-tokenSelector",
    cdata: "blog-editor-tokenComment",
    char: "blog-editor-tokenSelector",
    class: "blog-editor-tokenFunction",
    "class-name": "blog-editor-tokenFunction",
    comment: "blog-editor-tokenComment",
    constant: "blog-editor-tokenProperty",
    deleted: "blog-editor-tokenProperty",
    doctype: "blog-editor-tokenComment",
    entity: "blog-editor-tokenOperator",
    function: "blog-editor-tokenFunction",
    important: "blog-editor-tokenVariable",
    inserted: "blog-editor-tokenSelector",
    keyword: "blog-editor-tokenAttr",
    namespace: "blog-editor-tokenVariable",
    number: "blog-editor-tokenProperty",
    operator: "blog-editor-tokenOperator",
    prolog: "blog-editor-tokenComment",
    property: "blog-editor-tokenProperty",
    punctuation: "blog-editor-tokenPunctuation",
    regex: "blog-editor-tokenVariable",
    selector: "blog-editor-tokenSelector",
    string: "blog-editor-tokenSelector",
    symbol: "blog-editor-tokenProperty",
    tag: "blog-editor-tokenProperty",
    url: "blog-editor-tokenOperator",
    variable: "blog-editor-tokenVariable",
  },
  paragraph: "blog-editor-paragraph",
  quote: "blog-editor-quote",
  table: "blog-editor-table",
  tableCell: "blog-editor-table-cell",
  tableCellHeader: "blog-editor-table-cell-header",
  tableRow: "blog-editor-table-row",
};

export default editorTheme;
