import { VendorProfileResponse } from "./types"

// Mock Vendor Data
export const mockVendors: VendorProfileResponse[] = [
  {
    id: "vendor-1",
    userId: "user-1",
    email: "danang.arts@gmail.com",
    fullname: "Nguyen Van An",
    phoneNumber: "+84 905 123 456",
    avatarUrl: "https://ui-avatars.com/api/?name=Nguyen+Van+An&background=4F46E5&color=fff",
    role: "VENDOR",
    businessName: "Da Nang Arts Studio",
    description: "Traditional Vietnamese arts and crafts workshop provider with over 10 years of experience. We specialize in pottery, painting, and cultural workshops.",
    address: "123 Le Loi Street, Hai Chau District, Da Nang City",
    latitude: "16.0544",
    longitude: "108.2022",
    taxCode: "0401234567",
    bankName: "Vietcombank",
    bankAccountNumber: "1234567890",
    bankAccountName: "NGUYEN VAN AN",
    isVerifiedVendor: true,
    isActive: true,
    isBanned: false,
    createdAt: "2025-06-15T08:00:00Z",
    updatedAt: "2026-02-10T14:30:00Z",
    totalTemplates: 5,
    activeTemplates: 3,
    totalSessions: 24,
  },
  {
    id: "vendor-2",
    userId: "user-2",
    email: "saigon.cooking@gmail.com",
    fullname: "Tran Thi Binh",
    phoneNumber: "+84 906 234 567",
    avatarUrl: "https://ui-avatars.com/api/?name=Tran+Thi+Binh&background=10B981&color=fff",
    role: "VENDOR",
    businessName: "Saigon Cooking School",
    description: "Professional Vietnamese cooking classes for tourists and locals. Learn authentic recipes from experienced chefs.",
    address: "456 Nguyen Hue Boulevard, District 1, Ho Chi Minh City",
    latitude: "10.7769",
    longitude: "106.7009",
    taxCode: "0301234568",
    bankName: "Techcombank",
    bankAccountNumber: "9876543210",
    bankAccountName: "TRAN THI BINH",
    isVerifiedVendor: true,
    isActive: true,
    isBanned: false,
    createdAt: "2025-08-20T10:00:00Z",
    updatedAt: "2026-02-09T16:45:00Z",
    totalTemplates: 8,
    activeTemplates: 6,
    totalSessions: 45,
  },
  {
    id: "vendor-3",
    userId: "user-3",
    email: "hanoi.wellness@gmail.com",
    fullname: "Le Hoang Cuong",
    phoneNumber: "+84 907 345 678",
    avatarUrl: "https://ui-avatars.com/api/?name=Le+Hoang+Cuong&background=F59E0B&color=fff",
    role: "VENDOR",
    businessName: "Hanoi Wellness Center",
    description: "Yoga, meditation, and wellness workshops in the heart of Hanoi. Promoting healthy living and mindfulness.",
    address: "789 Ba Trieu Street, Hoan Kiem District, Hanoi",
    latitude: "21.0285",
    longitude: "105.8542",
    taxCode: "0101234569",
    bankName: "ACB Bank",
    bankAccountNumber: "5555666677",
    bankAccountName: "LE HOANG CUONG",
    isVerifiedVendor: true,
    isActive: true,
    isBanned: false,
    createdAt: "2025-09-10T09:30:00Z",
    updatedAt: "2026-02-08T11:20:00Z",
    totalTemplates: 4,
    activeTemplates: 3,
    totalSessions: 18,
  },
  {
    id: "vendor-4",
    userId: "user-4",
    email: "hue.culture@gmail.com",
    fullname: "Pham Minh Duc",
    phoneNumber: "+84 908 456 789",
    avatarUrl: "https://ui-avatars.com/api/?name=Pham+Minh+Duc&background=8B5CF6&color=fff",
    role: "VENDOR",
    businessName: "Hue Cultural Tours",
    description: "Traditional Hue cultural experiences including royal cuisine, traditional music, and craft workshops.",
    address: "321 Le Loi Street, Hue City",
    latitude: "16.4637",
    longitude: "107.5909",
    taxCode: null,
    bankName: "VietinBank",
    bankAccountNumber: "3333444455",
    bankAccountName: "PHAM MINH DUC",
    isVerifiedVendor: false,
    isActive: true,
    isBanned: false,
    createdAt: "2025-11-05T14:00:00Z",
    updatedAt: "2026-02-07T10:15:00Z",
    totalTemplates: 3,
    activeTemplates: 1,
    totalSessions: 6,
  },
  {
    id: "vendor-5",
    userId: "user-5",
    email: "nhatrang.diving@gmail.com",
    fullname: "Vo Thanh Em",
    phoneNumber: "+84 909 567 890",
    avatarUrl: "https://ui-avatars.com/api/?name=Vo+Thanh+Em&background=06B6D4&color=fff",
    role: "VENDOR",
    businessName: "Nha Trang Diving Adventures",
    description: "Scuba diving and water sports workshops. Certified instructors with safety-first approach.",
    address: "654 Tran Phu Street, Nha Trang City",
    latitude: "12.2388",
    longitude: "109.1967",
    taxCode: "0201234570",
    bankName: "Sacombank",
    bankAccountNumber: "7777888899",
    bankAccountName: "VO THANH EM",
    isVerifiedVendor: true,
    isActive: false, // Temporarily inactive
    isBanned: false,
    createdAt: "2025-10-12T11:30:00Z",
    updatedAt: "2026-02-05T09:00:00Z",
    totalTemplates: 2,
    activeTemplates: 0,
    totalSessions: 12,
  },
  {
    id: "vendor-6",
    userId: "user-6",
    email: "dalat.flowers@gmail.com",
    fullname: "Nguyen Thi Phuong",
    phoneNumber: "+84 910 678 901",
    avatarUrl: "https://ui-avatars.com/api/?name=Nguyen+Thi+Phuong&background=EC4899&color=fff",
    role: "VENDOR",
    businessName: "Dalat Flower Workshops",
    description: "Flower arrangement and gardening workshops in beautiful Dalat. Learn from expert florists.",
    address: "147 Phan Dinh Phung Street, Dalat City",
    latitude: "11.9404",
    longitude: "108.4583",
    taxCode: null,
    bankName: null,
    bankAccountNumber: null,
    bankAccountName: null,
    isVerifiedVendor: false,
    isActive: true,
    isBanned: false,
    createdAt: "2026-01-15T13:00:00Z",
    updatedAt: "2026-01-15T13:00:00Z",
    totalTemplates: 1,
    activeTemplates: 0,
    totalSessions: 0,
  },
  {
    id: "vendor-7",
    userId: "user-7",
    email: "cantho.boat@gmail.com",
    fullname: "Tran Van Gia",
    phoneNumber: "+84 911 789 012",
    avatarUrl: "https://ui-avatars.com/api/?name=Tran+Van+Gia&background=F97316&color=fff",
    role: "VENDOR",
    businessName: "Can Tho River Tours",
    description: "Mekong Delta river tours and floating market experiences. Authentic Vietnamese countryside.",
    address: "258 Hai Ba Trung Street, Can Tho City",
    latitude: "10.0452",
    longitude: "105.7469",
    taxCode: "0501234571",
    bankName: "MB Bank",
    bankAccountNumber: "2222333344",
    bankAccountName: "TRAN VAN GIA",
    isVerifiedVendor: true,
    isActive: true,
    isBanned: false,
    createdAt: "2025-07-22T10:30:00Z",
    updatedAt: "2026-02-06T15:30:00Z",
    totalTemplates: 6,
    activeTemplates: 4,
    totalSessions: 32,
  },
  {
    id: "vendor-8",
    userId: "user-8",
    email: "spam.workshop@fake.com",
    fullname: "Suspicious Vendor",
    phoneNumber: "+84 900 000 000",
    avatarUrl: "https://ui-avatars.com/api/?name=Suspicious+Vendor&background=EF4444&color=fff",
    role: "VENDOR",
    businessName: "Questionable Workshop Co.",
    description: "Suspicious activity detected. Multiple violations of terms of service.",
    address: "Unknown Address",
    latitude: null,
    longitude: null,
    taxCode: null,
    bankName: null,
    bankAccountNumber: null,
    bankAccountName: null,
    isVerifiedVendor: false,
    isActive: false,
    isBanned: true, // BANNED
    createdAt: "2026-01-20T08:00:00Z",
    updatedAt: "2026-01-25T16:00:00Z",
    totalTemplates: 0,
    activeTemplates: 0,
    totalSessions: 0,
  },
  {
    id: "vendor-9",
    userId: "user-9",
    email: "hoian.lantern@gmail.com",
    fullname: "Le Thi Hong",
    phoneNumber: "+84 912 890 123",
    avatarUrl: "https://ui-avatars.com/api/?name=Le+Thi+Hong&background=FBBF24&color=000",
    role: "VENDOR",
    businessName: "Hoi An Lantern Making",
    description: "Traditional Vietnamese lantern making workshops. Learn the ancient art passed down through generations.",
    address: "88 Nguyen Thai Hoc Street, Hoi An City",
    latitude: "15.8801",
    longitude: "108.3380",
    taxCode: "0601234572",
    bankName: "VPBank",
    bankAccountNumber: "4444555566",
    bankAccountName: "LE THI HONG",
    isVerifiedVendor: true,
    isActive: true,
    isBanned: false,
    createdAt: "2025-05-30T09:00:00Z",
    updatedAt: "2026-02-11T12:00:00Z",
    totalTemplates: 7,
    activeTemplates: 5,
    totalSessions: 38,
  },
  {
    id: "vendor-10",
    userId: "user-10",
    email: "vungtau.beach@gmail.com",
    fullname: "Hoang Van Khoa",
    phoneNumber: "+84 913 901 234",
    avatarUrl: "https://ui-avatars.com/api/?name=Hoang+Van+Khoa&background=14B8A6&color=fff",
    role: "VENDOR",
    businessName: "Vung Tau Beach Sports",
    description: "Beach sports and water activities. Surfing, kayaking, and beach volleyball lessons.",
    address: "777 Thuy Van Street, Vung Tau City",
    latitude: "10.3460",
    longitude: "107.0843",
    taxCode: null,
    bankName: "Agribank",
    bankAccountNumber: "6666777788",
    bankAccountName: "HOANG VAN KHOA",
    isVerifiedVendor: false,
    isActive: true,
    isBanned: false,
    createdAt: "2025-12-01T15:30:00Z",
    updatedAt: "2026-02-04T10:45:00Z",
    totalTemplates: 2,
    activeTemplates: 1,
    totalSessions: 8,
  },
]

// Calculate vendor stats from mock data
export const calculateVendorStats = (vendors: VendorProfileResponse[]) => {
  return {
    total: vendors.length,
    active: vendors.filter(v => v.isActive && !v.isBanned).length,
    banned: vendors.filter(v => v.isBanned).length,
    pendingVerification: vendors.filter(v => !v.isVerifiedVendor && !v.isBanned).length,
    verified: vendors.filter(v => v.isVerifiedVendor).length,
  }
}

export const mockVendorStats = calculateVendorStats(mockVendors)
